spring:
  datasource:
    url: jdbc:postgresql://localhost:5432/payment
    username: karen
    password: karen

    jpa:
      hibernate:
        ddl-auto: update
      database: postgresql
      database-platform: org.hibernate.dialect.PostgreSQLDialect
    kafka:
      producer:
        bootstrap-servers: localhost:9092
        key-serializer: org.apache.kafka.common.serialization.StringSerializer
        value-serializer: org.springframework.kafka.support.serializer.JsonSerializer
        properties:
          spring.json.type.mapping: paymentConfirmation:com.karen.ecommerce.notification.kafka.payment.PaymentConfirmation
  server:
    port: 8060